AWSTemplateFormatVersion: 2010-09-09
Description: Cloudhealth
Parameters:
  Environment:
    Description: The Environment
    Type: String
  ExternalId:
    Description: The Cloudhealth External ID
    Type: String
  CloudhealthAccountId:
    Description: The Cloudhealth External ID
    Type: String
Resources:
  CloudHealthRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: !Sub 
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "AWS": "arn:aws:iam::${CloudHealth}:root"
                },
                "Action": "sts:AssumeRole",
                "Condition": {
                  "StringEquals": {
                    "sts:ExternalId": "${External}"
                  }
                }
              }
            ]
          }
        - External: !Ref ExternalId
          CloudHealth: !Ref CloudhealthAccountId
      Path: /
      Policies:
        - PolicyName: CloudHealth
          PolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "autoscaling:Describe*",
                    "aws-portal:ViewBilling",
                    "aws-portal:ViewUsage",
                    "cloudformation:ListStacks",
                    "cloudformation:ListStackResources",
                    "cloudformation:DescribeStacks",
                    "cloudformation:DescribeStackEvents",
                    "cloudformation:DescribeStackResources",
                    "cloudformation:GetTemplate",
                    "cloudfront:Get*",
                    "cloudfront:List*",
                    "cloudtrail:DescribeTrails",
                    "cloudtrail:GetEventSelectors",
                    "cloudtrail:ListTags",
                    "cloudwatch:Describe*",
                    "cloudwatch:Get*",
                    "cloudwatch:List*",
                    "config:Get*",
                    "config:Describe*",
                    "config:Deliver*",
                    "config:List*",
                    "cur:Describe*",
                    "dms:Describe*",
                    "dms:List*",
                    "dynamodb:DescribeTable",
                    "dynamodb:List*",
                    "ec2:Describe*",
                    "ec2:GetReservedInstancesExchangeQuote",
                    "ecs:List*",
                    "ecs:Describe*",
                    "elasticache:Describe*",
                    "elasticache:ListTagsForResource",
                    "elasticbeanstalk:Check*",
                    "elasticbeanstalk:Describe*",
                    "elasticbeanstalk:List*",
                    "elasticbeanstalk:RequestEnvironmentInfo",
                    "elasticbeanstalk:RetrieveEnvironmentInfo",
                    "elasticfilesystem:Describe*",
                    "elasticloadbalancing:Describe*",
                    "elasticmapreduce:Describe*",
                    "elasticmapreduce:List*",
                    "es:List*",
                    "es:Describe*",
                    "firehose:ListDeliveryStreams",
                    "firehose:DescribeDeliveryStream",
                    "iam:List*",
                    "iam:Get*",
                    "iam:GenerateCredentialReport",
                    "kinesis:Describe*",
                    "kinesis:List*",
                    "kms:DescribeKey",
                    "kms:GetKeyRotationStatus",
                    "kms:ListKeys",
                    "lambda:List*",
                    "logs:Describe*",
                    "organizations:ListAccounts",
                    "organizations:ListTagsForResource",
                    "redshift:Describe*",
                    "route53:Get*",
                    "route53:List*",
                    "rds:Describe*",
                    "rds:ListTagsForResource",
                    "s3:GetBucketAcl",
                    "s3:GetBucketLocation",
                    "s3:GetBucketLogging",
                    "s3:GetBucketPolicy",
                    "s3:GetBucketPolicyStatus",
                    "s3:GetBucketPublicAccessBlock",
                    "s3:GetBucketTagging",
                    "s3:GetBucketVersioning",
                    "s3:GetBucketWebsite",
                    "s3:GetAccountPublicAccessBlock",
                    "s3:List*",
                    "sagemaker:Describe*",
                    "sagemaker:List*",
                    "savingsplans:DescribeSavingsPlans",
                    "sdb:GetAttributes",
                    "sdb:List*",
                    "ses:Get*",
                    "ses:List*",
                    "sns:Get*",
                    "sns:List*",
                    "sqs:GetQueueAttributes",
                    "sqs:ListQueues",
                    "storagegateway:List*",
                    "storagegateway:Describe*",
                    "workspaces:Describe*"
                  ],
                  "Resource": "*"
                }
              ]
            }
  CloudTrailPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !ImportValue 
        'Fn::Sub': '${Environment}-CloudTrail'
      Roles:
        - !Ref CloudHealthRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:List*'
              - 's3:Get*'
            Resource:
              - !ImportValue 
                'Fn::Sub': 'arn:aws:s3:::${Environment}-{CloudTrailBucket}/'
              - !ImportValue 
                'Fn::Sub': 'arn:aws:s3:::${Environment}-{CloudTrailBucket}/*'
Outputs:
  CloudTrailPolicy:
    Value: !Ref CloudTrailPolicy
    Export:
      Name: !Sub '${Environment}CloudTrailPolicy'
  CloudHealthRole:
    Value: !Ref CloudHealthRole
    Export:
      Name: CloudHealthRole
  CloudHealthRoleArn:
    Value: !GetAtt 
      - CloudHealthRole
      - Arn
    Export:
      Name: CloudHealthRoleArn
